# devops/develop/docker-compose.yml
version: '3.8'

services:
  codexy-api-develop:
    container_name: codexy-api-develop
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file:
      - .env.dev

    ports:
      - "5100:8080"
    networks:
      - codexy-network

networks:
  codexy-network:
    external: true  # ‚Üê Usa la red creada por databases/